<?php

require('DapiHelper.php');

$string = file_get_contents("./AE.json");
$validators = json_decode($string, true);

$beneficiary = [
    'type' =>  BeneficiaryType::LOCAL,
    'swiftCode' => 'ENBDFF',
    // sortCode: 'null',
    // bankName: 'null',
    'name' => 'ddds',
    'nickname' => 'DubaiXOXOXOX',
    'iban' => 'AE400260001015528953501',
    // accountNumber: 'null',
    // country: 'null',
    // branchName: 'null',
    // branchAddress: 'null',
    'address' => [
        'line1' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
        'line2' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
        'line3' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
    ],
    // 'addweeress' => [
    //     'line1' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
    //     'line2' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
    //     'line3' =>   'DubaiXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXXXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXX',
    // ]
];
$validator = $validators['CBDUAEAD'];
try {
    // print_r(DapiHelper::truncateCreateBeneficiary($validator['ABDIAEAD'], $beneficiary));
    print_r(DapiHelper::validateCreateBeneficiary($validator, $beneficiary));
} catch (\Exception $th) {
    print_r($th->getMessage());
    try {
        $beneficiary = DapiHelper::truncateCreateBeneficiary($validator, $beneficiary);
        print_r($beneficiary);
        print_r(DapiHelper::validateCreateBeneficiary($validator, $beneficiary));
    } catch (\Exception $th) {
        print_r($th->getMessage());
    }
}
